### ISSUE TITLE
The priority for operator "!=" was forgot

### ISSUE THREAD

**Issue by IvanHod** [lev4ek0/safe_eval#1]
In constant dict you forget `!=` operator.

Because of that the example `safe_evaluator.solve('(${a} != 1)', df)` gives an error

**Comment by lev4ek0** [comment]
will be fixed in 0.1.15 https://pypi.org/project/safe-evaluation/0.1.15/
https://github.com/lev4ek0/safe_eval/pull/2/commits/ae1e9a4db338093979a3796c6da1a13929a8edcc
